theme: jekyll-theme-architect
title: Brian Artschwager
description: I do things with computers on the internet.
linkedin_url: https://www.linkedin.com/in/brianartschwager/
twitter_url: https://twitter.com/artschwagerb